title:            Grace Yim
description:      Grace Yim
url:              # Site url.
signoff:          Grace Yim
google_analytics: 'UA-55275008-1'

links:
  - name:         About
    url:          /about
  - name:         Resume
    url:          /resume
    external:     false
  - name:         Projects
    url:          /projects
    external:     false
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
