# Site settings
title: Grace Yim
email: graceekyim@gmail.com
phone: 312.925.2566
description: > # this means to ignore newlines until "baseurl:"
  A former database specialist turned web developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://graceyim.com" # the base hostname & protocol for your site
twitter_username: graceekyim
github_username:  graceekyim
pages_list: 
Resume: '/resume'
Projects: '/projects'

# Build settings
markdown: kramdown